graph.add_edge('attraction', 'similarity', label='fostered by', horiz=False)
graph.add_edge('attraction', 'proximity', label='fostered by', horiz=False)
graph.add_edge('attraction', 'physical attraction', label='fostered by', horiz=False)
graph.add_edge('attraction', 'reciprocity', label='fostered by', horiz=False)
graph.add_edge('attraction', 'halo effect', label='causes', horiz=True)
graph.add_edge('attraction', 'affiliation', label='causes', horiz=True)
graph.add_edge('voluntary social relationships', 'attraction', label='fostered by', horiz=False)
graph.add_edge('friendship', 'voluntary social relationships', label='a kind of', horiz=False)
graph.add_edge('friendship', 'self-disclosure', label='involves', horiz=False)
graph.add_edge('self-disclosure', 'trust', label='involves', horiz=False)
graph.add_edge('similarity', 'homogamy in couples', label='called', horiz=False)
graph.add_edge('affiliation', 'prosocial behavior', label='a kind of', horiz=False)
graph.add_edge('prosocial behavior', 'people', label='positively impacts', horiz=False)
